//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.JavaScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sushi.JavaScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; (function (global, factory) {
        ///    if (typeof exports === &apos;object&apos; &amp;&amp; typeof module !== &apos;undefined&apos;)
        ///        module.exports = factory(global);
        ///    else if (typeof define === &apos;function&apos; &amp;&amp; define.amd)
        ///        define(factory());
        ///    else
        ///        factory(global);
        ///
        ///}(window, (function () {
        ///    &apos;use strict&apos;;
        ///
        ///    $$SCIPT_MODELS$$
        ///
        ///})));
        ///.
        /// </summary>
        internal static string dependency_injection {
            get {
                return ResourceManager.GetString("dependency_injection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function (window) {
        ///
        ///    $$SCIPT_MODELS$$
        ///
        ///})(window);.
        /// </summary>
        internal static string isolated_self_invokation {
            get {
                return ResourceManager.GetString("isolated_self_invokation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ReSharper disable UndeclaredGlobalVariableUsing
        ///// ReSharper disable InconsistentNaming
        ///// ReSharper disable WrongExpressionStatement
        ///// ReSharper disable UseOfImplicitGlobalInFunctionScope
        ///// ECMA 5 - $$TYPENAME$$
        ///
        ////**
        /// * $$SUMMARY$$
        /// *
        /// * Server-side generated model: $$TYPE_NAMESPACE$$.$$TYPENAME$$.
        /// * @name $$TYPENAME$$
        /// * @namespace $$TYPE_NAMESPACE$$.$$TYPENAME$$
        /// * @param {Object&lt;$$TYPENAME$$&gt;} [$$ARGUMENT_NAME$$] The object to convert to the match the &apos;$$TYPENAME$$&apos; class.
        /// */
        ///functi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V5 {
            get {
                return ResourceManager.GetString("V5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ReSharper disable UndeclaredGlobalVariableUsing
        ///// ReSharper disable InconsistentNaming
        ///// ReSharper disable WrongExpressionStatement
        ///// ReSharper disable UseOfImplicitGlobalInFunctionScope
        ///// ECMA 6 - $$TYPENAME$$
        ///
        ////**
        /// * $$SUMMARY$$
        /// *
        /// * Server-side generated model: $$TYPE_NAMESPACE$$.$$TYPENAME$$.
        /// * @name $$TYPENAME$$
        /// * @namespace $$TYPE_NAMESPACE$$.$$TYPENAME$$
        /// */
        ///class $$TYPENAME$$ $$INHERIT_TYPE$$ {
        ///	/**
        ///	 * $$SUMMARY$$
        ///	 *
        ///	 * Server-side generated model: $$TYPE_NAMESPACE$$.$$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V6 {
            get {
                return ResourceManager.GetString("V6", resourceCulture);
            }
        }
    }
}
